# GPU的简单使用

In [1]:
!nvidia-smi


Thu Jan 26 15:44:53 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 517.00       Driver Version: 517.00       CUDA Version: 11.7     |
|-------------------------------+----------------------+----------------------+
| GPU  Name            TCC/WDDM | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ... WDDM  | 00000000:01:00.0  On |                  N/A |
| N/A   46C    P0    15W /  N/A |    955MiB /  4096MiB |      3%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda')


(device(type='cpu'), device(type='cuda'))

In [3]:
# 查询gpu数量
torch.cuda.device_count()


1

In [6]:
# cpu上存储张量
x = torch.Tensor([1, 2, 3])
x.device


device(type='cuda', index=0)

In [10]:
# gpu上存储张量
Y = torch.ones(2, 3, device='cuda')
Y


tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

In [9]:
# 复制
Z = x.cuda()
Z


tensor([1., 2., 3.], device='cuda:0')

In [11]:
# 在同一块gpu上可以进行计算
Y+Z


tensor([[2., 3., 4.],
        [2., 3., 4.]], device='cuda:0')

## 神经网络与gpu

In [12]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device='cuda')


In [13]:
net(Z)


tensor([0.7963], device='cuda:0', grad_fn=<AddBackward0>)

In [14]:
# 确认模型参数存储在gpu上
net[0].weight.data.device



device(type='cuda', index=0)