# 预备知识

此文档用于熟悉 jupyter notebook 的操作


并学习预备知识

## 1. 数据操作

In [9]:
import torch

x = torch.arange(12)

x


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [10]:
x.shape


torch.Size([12])

In [11]:
x.numel()  # 获取张量中元素总数


12

In [12]:
X = x.reshape(3, 4)
X


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [13]:
torch.zeros((2, 3, 4))


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [14]:
torch.ones((2, 3, 4))


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [15]:
# 均值为0 标准差为1 的正态分布
torch.randn(3, 4)


tensor([[-0.2227,  0.7418, -0.5062, -2.7672],
        [ 0.1603,  0.7942,  0.6206, -0.4240],
        [ 1.2228, -1.5414, -0.3669,  0.1007]])

In [16]:
# 最外层的列表对应于轴0 内层的列表对应于轴1
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])


tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [17]:
# 按元素(elements)运算
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x+y, x-y, x*y, x/y, x**y


(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [18]:
torch.exp(x)


tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [19]:
# 张量连结(concatenate)
X = torch.arange(12, dtype=torch.float32).reshape((3, 4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [21]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [22]:
# 求和
X.sum()

tensor(66.)

In [23]:
# 广播机制 broadcasting mechanism
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b


(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [24]:
# 将两个不同大小的矩阵相加
# 将两个矩阵广播为一个更大的3x2矩阵, 再相加
a+b


tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [25]:
# 切片
# [-1]选择最后一个元素  [1:3]选择第二个和第三个元素
X[-1], X[1:3]


(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [27]:
X[1, 2] = 9
X


tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [28]:
X[0:2, :] = 12
X


tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [29]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)


(numpy.ndarray, torch.Tensor)